feat: beforeExec支持修改js代码 + 新增afterExec
kuitos/import-html-entry pull request #59
Opened 2020-10-27 06:55 UTC by bloody-ux

新增beforeExec/afterExec，传入脚本上下文信息，从而支持多script同时执行下，支持正确设置document.currentScript

增加beforeExec修改代码能力，实现外部可控的代码执行

2020-10-27 07:14 UTC, kuitos requested changes

2020-10-27 07:14 UTC, kuitos commented on index.d.ts
> +	beforeExec?: (code: string, script: string) => string | void;
beforeExec 跟 afterExec 配置为啥还要放 importEntry 里，是什么场景？只在调用 execScript 时传进来就可以了吧？

2020-10-27 07:14 UTC, kuitos commented on package.json
> +  "version": "1.10.0",
changelog 跟 版本号不用 pr 里改，发布的时候会自动处理

2020-10-27 07:14 UTC, kuitos commented on src/index.js
> +				let code = beforeExec(inlineScript, scriptSrc) || inlineScript;
```suggestion
				const rawCode = beforeExec(inlineScript, scriptSrc) || inlineScript;
```

prefer const

2020-10-27 07:14 UTC, kuitos commented on src/index.js
> +				code = getExecutableScript(scriptSrc, code, proxy, strictGlobal);
```suggestion
				const code = getExecutableScript(scriptSrc, rawCode, proxy, strictGlobal);
```

2020-10-27 07:17 UTC, kuitos commented
> 从而支持多script同时执行下，支持正确设置document.currentScript

这个是什么场景？现在的 beforeExec 应该也是支持的吧？
另外现在的 afterExec 的功能应该是跟 success 回调重叠了，之前 qiankun 是在 success 回调里处理 afterExec 的逻辑的

2020-10-27 09:01 UTC, bloody-ux commented on index.d.ts
> +	beforeExec?: (code: string, script: string) => string | void;
在importEntry的时候， 目前有些场景沙箱支持不太好，比如页面内的全局 var xxx定义， 打算在执行前，通过转码将其转化为window.xxx的形式来定义

2020-10-27 09:02 UTC, bloody-ux commented on package.json
> +  "version": "1.10.0",
我改回去

2020-10-27 09:07 UTC, bloody-ux commented on src/index.js
> +				code = getExecutableScript(scriptSrc, code, proxy, strictGlobal);
这里code会二次赋值， 我改一下改为
``` javascript
				const rawCode = beforeExec(inlineScript, scriptSrc) || inlineScript;
				const code = getExecutableScript(scriptSrc, rawCode, proxy, strictGlobal);

```

2020-10-27 12:33 UTC, kuitos approved these changes
Thanks for your nice work!

2020-10-27 12:34 UTC, merged

2020-11-06 22:32 UTC, easyzeng commented
你好，这个commit导致我们qiankun instance加载失败了，把getExecutableScript上移之后，缺了scriptSrc的type check, 如果是async script, 会fail在index line 47, 因为传进去的不是string是object
```
const isInlineCode = code => code.startsWith('<');
```

```
Uncaught TypeError: application 'XXX' died in status LOADING_SOURCE_CODE: t.startsWith is not a function
```