fix: 修复entry返回非utf-8编码的内容时，出现乱码的问题
kuitos/import-html-entry pull request #62
Opened 2020-11-19 12:32 UTC by bloody-ux

2020-11-20 07:10 UTC, kuitos commented on src/utils.js
> +	let charset = 'utf-8';
应该是要先通过 document.characterSet 读取下当前页面的编码，如果 entry 响应的编码跟当前一致，应该是不用转的，不一致才需要转

2020-11-20 07:10 UTC, kuitos requested changes

2020-11-20 07:10 UTC, kuitos commented on CHANGELOG.md
> +# Changelog
CHANGELOG 不用手写

2020-11-20 07:12 UTC, kuitos commented
感觉最好是给一个是否转换 entry 文本的配置，默认是关的？

2020-11-23 06:36 UTC, bloody-ux commented on src/utils.js
> +	let charset = 'utf-8';
`fetch`解码规则不是读取当前文档的字符编码，它一直是以utf-8作为默认解码的

2020-11-23 06:36 UTC, bloody-ux commented on CHANGELOG.md
> +# Changelog
好的，这个我删除下

2020-11-23 06:37 UTC, bloody-ux commented
> 感觉最好是给一个是否转换 entry 文本的配置，默认是关的？

嗯 我加个选项，避免出现regression

2020-11-23 08:45 UTC, kuitos requested changes

2020-11-23 08:45 UTC, kuitos commented on index.d.ts
> +	autoDetectCharset?: boolean;
这个配置我想了下，应该是隶属于 fetch 下面的，放到顶层有点奇怪。比如 fetch 的签名应该是：
```ts
fetch?: typeof window.fetch | { fn?: typeof window.fetch, autoDecodeResponse?: boolean }
```

代码里取 fetch 之前，需要先 normalize 一下，都变成对象配置的形式再去用，不然逻辑分支会比较多

2020-11-24 05:54 UTC, bloody-ux commented on index.d.ts
> +	autoDetectCharset?: boolean;
done

2020-11-24 06:19 UTC, kuitos approved these changes
Nice work!

2020-11-24 06:21 UTC, merged