fix: catch aborted error
kuitos/import-html-entry pull request #68
Opened 2021-03-19 14:06 UTC by carvinlo

捕捉 aborted 异常，如 [1330](https://github.com/umijs/qiankun/pull/1330)

2021-03-19 15:03 UTC, kuitos requested changes

2021-03-19 15:03 UTC, kuitos commented on src/index.js
> +			errorCallback();
异常 throw 出来，不要吞了

2021-03-20 00:53 UTC, carvinlo commented on src/index.js
> +			errorCallback();
ok

2021-04-29 09:27 UTC, kuitos approved these changes

2021-04-29 09:27 UTC, kuitos commented on src/index.js
> +			throw new Error(`${scriptUrl} load failed (${e.name}: ${e.message})`);
```suggestion
			throw e;
```

error 直接原样 throw，从而保留原来的异常栈信息

2021-04-29 09:27 UTC, merged