Add document details
kuitos/import-html-entry pull request #70
Opened 2021-04-15 02:20 UTC by guibwl

Add API list：

- importHTML
- importEntry
- execScripts

2021-04-29 04:17 UTC, kuitos commented on README.md
> +Treats the index html as manifest and loads the assets(css,js), export last property on the `window` or `proxy window` which set by the entry script.
不要在用户文档透出代码实现细节，实现细节可能会变

2021-04-29 04:18 UTC, kuitos requested changes

2021-04-29 04:18 UTC, kuitos commented on README.md
> +	- getPublicPath - `(entry: Entry) => string` - optional, Customize the assets public path.
这个缩进好像有点问题？

2021-05-04 17:42 UTC, guibwl commented on README.md
> +Treats the index html as manifest and loads the assets(css,js), export last property on the `window` or `proxy window` which set by the entry script.
这里已经修过回去了。

2021-05-04 17:43 UTC, guibwl commented on README.md
> +	- getPublicPath - `(entry: Entry) => string` - optional, Customize the assets public path.
这个锁进是个 Tab，已经改成和其他一致的 4个空格了。

2021-11-23 12:39 UTC, merged