feat: again load source fail should catch error
kuitos/import-html-entry pull request #97
Opened 2023-09-21 03:17 UTC by qiYuei

问题描述 可看此[issue](url)

2023-10-09 16:23 UTC, kuitos approved these changes
LGTM

2023-10-09 16:26 UTC, kuitos requested changes

2023-10-09 16:26 UTC, kuitos commented on src/index.js
> +			error();
这里 catch 的话 getExternalScripts 那里就不要再 catch 了，不然 error callback 会被调用两次

2023-10-10 03:07 UTC, qiYuei commented on src/index.js
> +			error();
确实. Done!

2023-10-10 03:14 UTC, kuitos requested changes

2023-10-10 03:14 UTC, kuitos commented on src/index.js
> +		}))
直接删了就行，包括入参及调用那里的代码

2023-10-10 03:30 UTC, qiYuei commented on src/index.js
> +		}))
done

2023-10-10 06:14 UTC, kuitos commented on src/index.js
> +		}))
```suggestion
		}));
```

2023-10-10 06:15 UTC, kuitos approved these changes
LGTM

2023-10-10 06:20 UTC, merged